version: '3'

services:
  database:
    container_name: database
    build:
      context: ./docker/database/
      dockerfile: Dockerfile
    image: landrepo/database:0.0.0
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      # NOTE: データベースのログイン情報等
      POSTGRES_USER: 'landrepo_user'
      POSTGRES_PASSWORD: 'landrepo_pwd'
      POSTGRES_DB: 'landrepo'
    logging:
      driver: json-file
      options:
        max-size: '1m'
        max-file: '1'

  # NOTE: https://qiita.com/kanemu/items/1f2da063c7e5b5477502
  mailer:
    container_name: mailer
    image: kanemu/maildev-with-iconv
    ports:
      - '1080:80'
      - '1025:25' #テスト用SMTPポート

volumes:
  database_data:
    driver: local
